apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: factorial-mn
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      name: factorial-mn
  template:
    metadata:
      labels:
        name: factorial-mn
    spec:
      containers:
        - image: domix/factorial-service:0.0.5
          name: factorial
          imagePullPolicy: Always
          resources:
            limits:
              memory: "320Mi"
              cpu: "200m"
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /factorial/
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /factorial/
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 2
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: factorial-mn
spec:
  maxReplicas: 8
  minReplicas: 1
  targetCPUUtilizationPercentage: 75
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: factorial-mn