apiVersion: v1
kind: Service
metadata:
  name: factorial-srv-np
  labels:
    name: factorial
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30125
      protocol: TCP
      name: app
  selector:
    name: factorial
---
apiVersion: v1
kind: Service
metadata:
  name: factorial
  labels:
    name: factorial
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: app
  selector:
    name: factorial