apiVersion: v1
kind: Service
metadata:
  name: factorial-mn
  labels:
    name: factorial-mn
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: app
  selector:
    name: factorial-mn